// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const companyExistsInWorkspace = `-- name: CompanyExistsInWorkspace :one
SELECT EXISTS(
    SELECT 1
    FROM "Company"
    WHERE "id" = $1
      AND "workspaceId" = $2
      AND "deletedAt" IS NULL
) AS "exists"
`

type CompanyExistsInWorkspaceParams struct {
	ID          string `json:"id"`
	WorkspaceId string `json:"workspaceId"`
}

func (q *Queries) CompanyExistsInWorkspace(ctx context.Context, arg CompanyExistsInWorkspaceParams) (bool, error) {
	row := q.db.QueryRow(ctx, companyExistsInWorkspace, arg.ID, arg.WorkspaceId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO "Company" (
    "id", "workspaceId", "name", "website", "linkedin",
    "legalName", "phone", "instagram", "policyUrl", "socialUrls",
    "addressLine", "city", "state", "country", "timezone",
    "currency", "locale", "businessHours", "supportHours",
    "size", "revenue", "companyScore", "lifecycleStage",
    "assignedToId", "createdById", "updatedById",
    "createdAt", "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19,
    $20, $21, $22, $23,
    $24, $25, $26,
    $27, $28
)
RETURNING 
    "id", "workspaceId", "name", "website", "linkedin",
    "legalName", "phone", "instagram", "policyUrl", "socialUrls",
    "addressLine", "city", "state", "country", "timezone",
    "currency", "locale", "businessHours", "supportHours",
    "deletedAt", "deletedById", "size", "revenue",
    "companyScore", "lifecycleStage", "assignedToId",
    "createdById", "updatedById", "createdAt", "updatedAt"
`

type CreateCompanyParams struct {
	ID             string                `json:"id"`
	WorkspaceId    string                `json:"workspaceId"`
	Name           string                `json:"name"`
	Website        *string               `json:"website"`
	Linkedin       *string               `json:"linkedin"`
	LegalName      *string               `json:"legalName"`
	Phone          *string               `json:"phone"`
	Instagram      *string               `json:"instagram"`
	PolicyUrl      *string               `json:"policyUrl"`
	SocialUrls     []byte                `json:"socialUrls"`
	AddressLine    *string               `json:"addressLine"`
	City           *string               `json:"city"`
	State          *string               `json:"state"`
	Country        *string               `json:"country"`
	Timezone       *string               `json:"timezone"`
	Currency       *string               `json:"currency"`
	Locale         *string               `json:"locale"`
	BusinessHours  []byte                `json:"businessHours"`
	SupportHours   []byte                `json:"supportHours"`
	Size           NullCompanySize       `json:"size"`
	Revenue        *float64              `json:"revenue"`
	CompanyScore   int32                 `json:"companyScore"`
	LifecycleStage CompanyLifecycleStage `json:"lifecycleStage"`
	AssignedToId   *string               `json:"assignedToId"`
	CreatedById    *string               `json:"createdById"`
	UpdatedById    *string               `json:"updatedById"`
	CreatedAt      pgtype.Timestamp      `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp      `json:"updatedAt"`
}

type CreateCompanyRow struct {
	ID             string                `json:"id"`
	WorkspaceId    string                `json:"workspaceId"`
	Name           string                `json:"name"`
	Website        *string               `json:"website"`
	Linkedin       *string               `json:"linkedin"`
	LegalName      *string               `json:"legalName"`
	Phone          *string               `json:"phone"`
	Instagram      *string               `json:"instagram"`
	PolicyUrl      *string               `json:"policyUrl"`
	SocialUrls     []byte                `json:"socialUrls"`
	AddressLine    *string               `json:"addressLine"`
	City           *string               `json:"city"`
	State          *string               `json:"state"`
	Country        *string               `json:"country"`
	Timezone       *string               `json:"timezone"`
	Currency       *string               `json:"currency"`
	Locale         *string               `json:"locale"`
	BusinessHours  []byte                `json:"businessHours"`
	SupportHours   []byte                `json:"supportHours"`
	DeletedAt      pgtype.Timestamp      `json:"deletedAt"`
	DeletedById    *string               `json:"deletedById"`
	Size           NullCompanySize       `json:"size"`
	Revenue        *float64              `json:"revenue"`
	CompanyScore   int32                 `json:"companyScore"`
	LifecycleStage CompanyLifecycleStage `json:"lifecycleStage"`
	AssignedToId   *string               `json:"assignedToId"`
	CreatedById    *string               `json:"createdById"`
	UpdatedById    *string               `json:"updatedById"`
	CreatedAt      pgtype.Timestamp      `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp      `json:"updatedAt"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (CreateCompanyRow, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.WorkspaceId,
		arg.Name,
		arg.Website,
		arg.Linkedin,
		arg.LegalName,
		arg.Phone,
		arg.Instagram,
		arg.PolicyUrl,
		arg.SocialUrls,
		arg.AddressLine,
		arg.City,
		arg.State,
		arg.Country,
		arg.Timezone,
		arg.Currency,
		arg.Locale,
		arg.BusinessHours,
		arg.SupportHours,
		arg.Size,
		arg.Revenue,
		arg.CompanyScore,
		arg.LifecycleStage,
		arg.AssignedToId,
		arg.CreatedById,
		arg.UpdatedById,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateCompanyRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.Name,
		&i.Website,
		&i.Linkedin,
		&i.LegalName,
		&i.Phone,
		&i.Instagram,
		&i.PolicyUrl,
		&i.SocialUrls,
		&i.AddressLine,
		&i.City,
		&i.State,
		&i.Country,
		&i.Timezone,
		&i.Currency,
		&i.Locale,
		&i.BusinessHours,
		&i.SupportHours,
		&i.DeletedAt,
		&i.DeletedById,
		&i.Size,
		&i.Revenue,
		&i.CompanyScore,
		&i.LifecycleStage,
		&i.AssignedToId,
		&i.CreatedById,
		&i.UpdatedById,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one

SELECT 
    "id", "workspaceId", "name", "website", "linkedin",
    "legalName", "phone", "instagram", "policyUrl", "socialUrls",
    "addressLine", "city", "state", "country", "timezone",
    "currency", "locale", "businessHours", "supportHours",
    "deletedAt", "deletedById", "size", "revenue",
    "companyScore", "lifecycleStage", "assignedToId",
    "createdById", "updatedById", "createdAt", "updatedAt"
FROM "Company"
WHERE "id" = $1
  AND "workspaceId" = $2
  AND "deletedAt" IS NULL
`

type GetCompanyParams struct {
	ID          string `json:"id"`
	WorkspaceId string `json:"workspaceId"`
}

type GetCompanyRow struct {
	ID             string                `json:"id"`
	WorkspaceId    string                `json:"workspaceId"`
	Name           string                `json:"name"`
	Website        *string               `json:"website"`
	Linkedin       *string               `json:"linkedin"`
	LegalName      *string               `json:"legalName"`
	Phone          *string               `json:"phone"`
	Instagram      *string               `json:"instagram"`
	PolicyUrl      *string               `json:"policyUrl"`
	SocialUrls     []byte                `json:"socialUrls"`
	AddressLine    *string               `json:"addressLine"`
	City           *string               `json:"city"`
	State          *string               `json:"state"`
	Country        *string               `json:"country"`
	Timezone       *string               `json:"timezone"`
	Currency       *string               `json:"currency"`
	Locale         *string               `json:"locale"`
	BusinessHours  []byte                `json:"businessHours"`
	SupportHours   []byte                `json:"supportHours"`
	DeletedAt      pgtype.Timestamp      `json:"deletedAt"`
	DeletedById    *string               `json:"deletedById"`
	Size           NullCompanySize       `json:"size"`
	Revenue        *float64              `json:"revenue"`
	CompanyScore   int32                 `json:"companyScore"`
	LifecycleStage CompanyLifecycleStage `json:"lifecycleStage"`
	AssignedToId   *string               `json:"assignedToId"`
	CreatedById    *string               `json:"createdById"`
	UpdatedById    *string               `json:"updatedById"`
	CreatedAt      pgtype.Timestamp      `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp      `json:"updatedAt"`
}

// =====================================================
// COMPANIES QUERIES - SQLc Generated
// =====================================================
// Tabela: "Company"
// Schema: camelCase com aspas duplas
// IDs: TEXT (não UUID)
// ENUMs: CompanyLifecycleStage, CompanySize (UPPERCASE)
// =====================================================
func (q *Queries) GetCompany(ctx context.Context, arg GetCompanyParams) (GetCompanyRow, error) {
	row := q.db.QueryRow(ctx, getCompany, arg.ID, arg.WorkspaceId)
	var i GetCompanyRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.Name,
		&i.Website,
		&i.Linkedin,
		&i.LegalName,
		&i.Phone,
		&i.Instagram,
		&i.PolicyUrl,
		&i.SocialUrls,
		&i.AddressLine,
		&i.City,
		&i.State,
		&i.Country,
		&i.Timezone,
		&i.Currency,
		&i.Locale,
		&i.BusinessHours,
		&i.SupportHours,
		&i.DeletedAt,
		&i.DeletedById,
		&i.Size,
		&i.Revenue,
		&i.CompanyScore,
		&i.LifecycleStage,
		&i.AssignedToId,
		&i.CreatedById,
		&i.UpdatedById,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT 
    "id", "workspaceId", "name", "website", "linkedin",
    "legalName", "phone", "instagram", "policyUrl", "socialUrls",
    "addressLine", "city", "state", "country", "timezone",
    "currency", "locale", "businessHours", "supportHours",
    "deletedAt", "deletedById", "size", "revenue",
    "companyScore", "lifecycleStage", "assignedToId",
    "createdById", "updatedById", "createdAt", "updatedAt"
FROM "Company"
WHERE "workspaceId" = $1
  AND "deletedAt" IS NULL
  AND ($2::TEXT IS NULL OR "lifecycleStage"::TEXT = $2)
  AND ($3::TEXT IS NULL OR "size"::TEXT = $3)
  AND ($4::TEXT IS NULL OR "assignedToId" = $4)
  AND ($5::TEXT IS NULL OR to_tsvector('simple', "name" || ' ' || COALESCE("website", '')) @@ plainto_tsquery('simple', $5))
  AND ($6::TIMESTAMP IS NULL OR "createdAt" < $6)
ORDER BY "createdAt" DESC
LIMIT $7
`

type ListCompaniesParams struct {
	WorkspaceId string           `json:"workspaceId"`
	Column2     string           `json:"column2"`
	Column3     string           `json:"column3"`
	Column4     string           `json:"column4"`
	Column5     string           `json:"column5"`
	Column6     pgtype.Timestamp `json:"column6"`
	Limit       int32            `json:"limit"`
}

type ListCompaniesRow struct {
	ID             string                `json:"id"`
	WorkspaceId    string                `json:"workspaceId"`
	Name           string                `json:"name"`
	Website        *string               `json:"website"`
	Linkedin       *string               `json:"linkedin"`
	LegalName      *string               `json:"legalName"`
	Phone          *string               `json:"phone"`
	Instagram      *string               `json:"instagram"`
	PolicyUrl      *string               `json:"policyUrl"`
	SocialUrls     []byte                `json:"socialUrls"`
	AddressLine    *string               `json:"addressLine"`
	City           *string               `json:"city"`
	State          *string               `json:"state"`
	Country        *string               `json:"country"`
	Timezone       *string               `json:"timezone"`
	Currency       *string               `json:"currency"`
	Locale         *string               `json:"locale"`
	BusinessHours  []byte                `json:"businessHours"`
	SupportHours   []byte                `json:"supportHours"`
	DeletedAt      pgtype.Timestamp      `json:"deletedAt"`
	DeletedById    *string               `json:"deletedById"`
	Size           NullCompanySize       `json:"size"`
	Revenue        *float64              `json:"revenue"`
	CompanyScore   int32                 `json:"companyScore"`
	LifecycleStage CompanyLifecycleStage `json:"lifecycleStage"`
	AssignedToId   *string               `json:"assignedToId"`
	CreatedById    *string               `json:"createdById"`
	UpdatedById    *string               `json:"updatedById"`
	CreatedAt      pgtype.Timestamp      `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp      `json:"updatedAt"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies,
		arg.WorkspaceId,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesRow{}
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceId,
			&i.Name,
			&i.Website,
			&i.Linkedin,
			&i.LegalName,
			&i.Phone,
			&i.Instagram,
			&i.PolicyUrl,
			&i.SocialUrls,
			&i.AddressLine,
			&i.City,
			&i.State,
			&i.Country,
			&i.Timezone,
			&i.Currency,
			&i.Locale,
			&i.BusinessHours,
			&i.SupportHours,
			&i.DeletedAt,
			&i.DeletedById,
			&i.Size,
			&i.Revenue,
			&i.CompanyScore,
			&i.LifecycleStage,
			&i.AssignedToId,
			&i.CreatedById,
			&i.UpdatedById,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCompany = `-- name: SoftDeleteCompany :exec
UPDATE "Company"
SET
    "deletedAt" = $3,
    "deletedById" = $4,
    "updatedAt" = $3
WHERE "id" = $1
  AND "workspaceId" = $2
  AND "deletedAt" IS NULL
`

type SoftDeleteCompanyParams struct {
	ID          string           `json:"id"`
	WorkspaceId string           `json:"workspaceId"`
	DeletedAt   pgtype.Timestamp `json:"deletedAt"`
	DeletedById *string          `json:"deletedById"`
}

func (q *Queries) SoftDeleteCompany(ctx context.Context, arg SoftDeleteCompanyParams) error {
	_, err := q.db.Exec(ctx, softDeleteCompany,
		arg.ID,
		arg.WorkspaceId,
		arg.DeletedAt,
		arg.DeletedById,
	)
	return err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE "Company"
SET
    "name" = COALESCE($3, "name"),
    "website" = COALESCE($4, "website"),
    "linkedin" = COALESCE($5, "linkedin"),
    "legalName" = COALESCE($6, "legalName"),
    "phone" = COALESCE($7, "phone"),
    "instagram" = COALESCE($8, "instagram"),
    "policyUrl" = COALESCE($9, "policyUrl"),
    "socialUrls" = COALESCE($10, "socialUrls"),
    "addressLine" = COALESCE($11, "addressLine"),
    "city" = COALESCE($12, "city"),
    "state" = COALESCE($13, "state"),
    "country" = COALESCE($14, "country"),
    "timezone" = COALESCE($15, "timezone"),
    "currency" = COALESCE($16, "currency"),
    "locale" = COALESCE($17, "locale"),
    "businessHours" = COALESCE($18, "businessHours"),
    "supportHours" = COALESCE($19, "supportHours"),
    "size" = COALESCE($20, "size"),
    "revenue" = COALESCE($21, "revenue"),
    "companyScore" = COALESCE($22, "companyScore"),
    "lifecycleStage" = COALESCE($23, "lifecycleStage"),
    "assignedToId" = COALESCE($24, "assignedToId"),
    "updatedById" = $25,
    "updatedAt" = $26
WHERE "id" = $1
  AND "workspaceId" = $2
  AND "deletedAt" IS NULL
  AND "updatedAt" = $27
RETURNING 
    "id", "workspaceId", "name", "website", "linkedin",
    "legalName", "phone", "instagram", "policyUrl", "socialUrls",
    "addressLine", "city", "state", "country", "timezone",
    "currency", "locale", "businessHours", "supportHours",
    "deletedAt", "deletedById", "size", "revenue",
    "companyScore", "lifecycleStage", "assignedToId",
    "createdById", "updatedById", "createdAt", "updatedAt"
`

type UpdateCompanyParams struct {
	ID             string                `json:"id"`
	WorkspaceId    string                `json:"workspaceId"`
	Name           string                `json:"name"`
	Website        *string               `json:"website"`
	Linkedin       *string               `json:"linkedin"`
	LegalName      *string               `json:"legalName"`
	Phone          *string               `json:"phone"`
	Instagram      *string               `json:"instagram"`
	PolicyUrl      *string               `json:"policyUrl"`
	SocialUrls     []byte                `json:"socialUrls"`
	AddressLine    *string               `json:"addressLine"`
	City           *string               `json:"city"`
	State          *string               `json:"state"`
	Country        *string               `json:"country"`
	Timezone       *string               `json:"timezone"`
	Currency       *string               `json:"currency"`
	Locale         *string               `json:"locale"`
	BusinessHours  []byte                `json:"businessHours"`
	SupportHours   []byte                `json:"supportHours"`
	Size           NullCompanySize       `json:"size"`
	Revenue        *float64              `json:"revenue"`
	CompanyScore   int32                 `json:"companyScore"`
	LifecycleStage CompanyLifecycleStage `json:"lifecycleStage"`
	AssignedToId   *string               `json:"assignedToId"`
	UpdatedById    *string               `json:"updatedById"`
	UpdatedAt      pgtype.Timestamp      `json:"updatedAt"`
	UpdatedAt_2    pgtype.Timestamp      `json:"updatedAt2"`
}

type UpdateCompanyRow struct {
	ID             string                `json:"id"`
	WorkspaceId    string                `json:"workspaceId"`
	Name           string                `json:"name"`
	Website        *string               `json:"website"`
	Linkedin       *string               `json:"linkedin"`
	LegalName      *string               `json:"legalName"`
	Phone          *string               `json:"phone"`
	Instagram      *string               `json:"instagram"`
	PolicyUrl      *string               `json:"policyUrl"`
	SocialUrls     []byte                `json:"socialUrls"`
	AddressLine    *string               `json:"addressLine"`
	City           *string               `json:"city"`
	State          *string               `json:"state"`
	Country        *string               `json:"country"`
	Timezone       *string               `json:"timezone"`
	Currency       *string               `json:"currency"`
	Locale         *string               `json:"locale"`
	BusinessHours  []byte                `json:"businessHours"`
	SupportHours   []byte                `json:"supportHours"`
	DeletedAt      pgtype.Timestamp      `json:"deletedAt"`
	DeletedById    *string               `json:"deletedById"`
	Size           NullCompanySize       `json:"size"`
	Revenue        *float64              `json:"revenue"`
	CompanyScore   int32                 `json:"companyScore"`
	LifecycleStage CompanyLifecycleStage `json:"lifecycleStage"`
	AssignedToId   *string               `json:"assignedToId"`
	CreatedById    *string               `json:"createdById"`
	UpdatedById    *string               `json:"updatedById"`
	CreatedAt      pgtype.Timestamp      `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp      `json:"updatedAt"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (UpdateCompanyRow, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.WorkspaceId,
		arg.Name,
		arg.Website,
		arg.Linkedin,
		arg.LegalName,
		arg.Phone,
		arg.Instagram,
		arg.PolicyUrl,
		arg.SocialUrls,
		arg.AddressLine,
		arg.City,
		arg.State,
		arg.Country,
		arg.Timezone,
		arg.Currency,
		arg.Locale,
		arg.BusinessHours,
		arg.SupportHours,
		arg.Size,
		arg.Revenue,
		arg.CompanyScore,
		arg.LifecycleStage,
		arg.AssignedToId,
		arg.UpdatedById,
		arg.UpdatedAt,
		arg.UpdatedAt_2,
	)
	var i UpdateCompanyRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.Name,
		&i.Website,
		&i.Linkedin,
		&i.LegalName,
		&i.Phone,
		&i.Instagram,
		&i.PolicyUrl,
		&i.SocialUrls,
		&i.AddressLine,
		&i.City,
		&i.State,
		&i.Country,
		&i.Timezone,
		&i.Currency,
		&i.Locale,
		&i.BusinessHours,
		&i.SupportHours,
		&i.DeletedAt,
		&i.DeletedById,
		&i.Size,
		&i.Revenue,
		&i.CompanyScore,
		&i.LifecycleStage,
		&i.AssignedToId,
		&i.CreatedById,
		&i.UpdatedById,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
