// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompanyLifecycleStage string

const (
	CompanyLifecycleStageLEAD     CompanyLifecycleStage = "LEAD"
	CompanyLifecycleStageMQL      CompanyLifecycleStage = "MQL"
	CompanyLifecycleStageSQL      CompanyLifecycleStage = "SQL"
	CompanyLifecycleStageCUSTOMER CompanyLifecycleStage = "CUSTOMER"
	CompanyLifecycleStageCHURNED  CompanyLifecycleStage = "CHURNED"
)

func (e *CompanyLifecycleStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyLifecycleStage(s)
	case string:
		*e = CompanyLifecycleStage(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyLifecycleStage: %T", src)
	}
	return nil
}

type NullCompanyLifecycleStage struct {
	CompanyLifecycleStage CompanyLifecycleStage `json:"CompanyLifecycleStage"`
	Valid                 bool                  `json:"valid"` // Valid is true if CompanyLifecycleStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyLifecycleStage) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyLifecycleStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyLifecycleStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyLifecycleStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyLifecycleStage), nil
}

type CompanySize string

const (
	CompanySizeSTARTUP    CompanySize = "STARTUP"
	CompanySizeSMB        CompanySize = "SMB"
	CompanySizeMIDMARKET  CompanySize = "MID_MARKET"
	CompanySizeENTERPRISE CompanySize = "ENTERPRISE"
)

func (e *CompanySize) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanySize(s)
	case string:
		*e = CompanySize(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanySize: %T", src)
	}
	return nil
}

type NullCompanySize struct {
	CompanySize CompanySize `json:"CompanySize"`
	Valid       bool        `json:"valid"` // Valid is true if CompanySize is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanySize) Scan(value interface{}) error {
	if value == nil {
		ns.CompanySize, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanySize.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanySize) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanySize), nil
}

type ContactLifecycleStage string

const (
	ContactLifecycleStageLEAD        ContactLifecycleStage = "LEAD"
	ContactLifecycleStageMQL         ContactLifecycleStage = "MQL"
	ContactLifecycleStageSQL         ContactLifecycleStage = "SQL"
	ContactLifecycleStageOPPORTUNITY ContactLifecycleStage = "OPPORTUNITY"
	ContactLifecycleStageCUSTOMER    ContactLifecycleStage = "CUSTOMER"
	ContactLifecycleStageEVANGELIST  ContactLifecycleStage = "EVANGELIST"
)

func (e *ContactLifecycleStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContactLifecycleStage(s)
	case string:
		*e = ContactLifecycleStage(s)
	default:
		return fmt.Errorf("unsupported scan type for ContactLifecycleStage: %T", src)
	}
	return nil
}

type NullContactLifecycleStage struct {
	ContactLifecycleStage ContactLifecycleStage `json:"ContactLifecycleStage"`
	Valid                 bool                  `json:"valid"` // Valid is true if ContactLifecycleStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContactLifecycleStage) Scan(value interface{}) error {
	if value == nil {
		ns.ContactLifecycleStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContactLifecycleStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContactLifecycleStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContactLifecycleStage), nil
}

type DealStage string

const (
	DealStageOPEN DealStage = "OPEN"
	DealStageWON  DealStage = "WON"
	DealStageLOST DealStage = "LOST"
)

func (e *DealStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DealStage(s)
	case string:
		*e = DealStage(s)
	default:
		return fmt.Errorf("unsupported scan type for DealStage: %T", src)
	}
	return nil
}

type NullDealStage struct {
	DealStage DealStage `json:"DealStage"`
	Valid     bool      `json:"valid"` // Valid is true if DealStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDealStage) Scan(value interface{}) error {
	if value == nil {
		ns.DealStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DealStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDealStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DealStage), nil
}

type PipelineType string

const (
	PipelineTypeTASK    PipelineType = "TASK"
	PipelineTypeDEAL    PipelineType = "DEAL"
	PipelineTypeTICKET  PipelineType = "TICKET"
	PipelineTypeCONTACT PipelineType = "CONTACT"
)

func (e *PipelineType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PipelineType(s)
	case string:
		*e = PipelineType(s)
	default:
		return fmt.Errorf("unsupported scan type for PipelineType: %T", src)
	}
	return nil
}

type NullPipelineType struct {
	PipelineType PipelineType `json:"PipelineType"`
	Valid        bool         `json:"valid"` // Valid is true if PipelineType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPipelineType) Scan(value interface{}) error {
	if value == nil {
		ns.PipelineType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PipelineType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPipelineType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PipelineType), nil
}

type Priority string

const (
	PriorityLOW    Priority = "LOW"
	PriorityMEDIUM Priority = "MEDIUM"
	PriorityHIGH   Priority = "HIGH"
	PriorityURGENT Priority = "URGENT"
)

func (e *Priority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Priority(s)
	case string:
		*e = Priority(s)
	default:
		return fmt.Errorf("unsupported scan type for Priority: %T", src)
	}
	return nil
}

type NullPriority struct {
	Priority Priority `json:"Priority"`
	Valid    bool     `json:"valid"` // Valid is true if Priority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriority) Scan(value interface{}) error {
	if value == nil {
		ns.Priority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Priority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Priority), nil
}

type StageGroup string

const (
	StageGroupOPEN   StageGroup = "OPEN"
	StageGroupACTIVE StageGroup = "ACTIVE"
	StageGroupDONE   StageGroup = "DONE"
	StageGroupCLOSED StageGroup = "CLOSED"
)

func (e *StageGroup) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StageGroup(s)
	case string:
		*e = StageGroup(s)
	default:
		return fmt.Errorf("unsupported scan type for StageGroup: %T", src)
	}
	return nil
}

type NullStageGroup struct {
	StageGroup StageGroup `json:"StageGroup"`
	Valid      bool       `json:"valid"` // Valid is true if StageGroup is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStageGroup) Scan(value interface{}) error {
	if value == nil {
		ns.StageGroup, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StageGroup.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStageGroup) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StageGroup), nil
}

type TagCategory string

const (
	TagCategoryPRIORITY      TagCategory = "PRIORITY"
	TagCategorySTATUS        TagCategory = "STATUS"
	TagCategoryTEMPERATURE   TagCategory = "TEMPERATURE"
	TagCategoryTYPE          TagCategory = "TYPE"
	TagCategoryQUALIFICATION TagCategory = "QUALIFICATION"
)

func (e *TagCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TagCategory(s)
	case string:
		*e = TagCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TagCategory: %T", src)
	}
	return nil
}

type NullTagCategory struct {
	TagCategory TagCategory `json:"TagCategory"`
	Valid       bool        `json:"valid"` // Valid is true if TagCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTagCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TagCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TagCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTagCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TagCategory), nil
}

type TaskStatus string

const (
	TaskStatusTODO       TaskStatus = "TODO"
	TaskStatusINPROGRESS TaskStatus = "IN_PROGRESS"
	TaskStatusDONE       TaskStatus = "DONE"
	TaskStatusCANCELLED  TaskStatus = "CANCELLED"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"TaskStatus"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TaskType string

const (
	TaskTypeCALL     TaskType = "CALL"
	TaskTypeEMAIL    TaskType = "EMAIL"
	TaskTypeMEETING  TaskType = "MEETING"
	TaskTypeFOLLOWUP TaskType = "FOLLOWUP"
	TaskTypeOTHER    TaskType = "OTHER"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType `json:"TaskType"`
	Valid    bool     `json:"valid"` // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type AdminRole struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type AuditLog struct {
	ID          string           `json:"id"`
	WorkspaceId string           `json:"workspaceId"`
	UserId      string           `json:"userId"`
	Action      string           `json:"action"`
	EntityType  string           `json:"entityType"`
	EntityId    string           `json:"entityId"`
	Metadata    []byte           `json:"metadata"`
	IpAddress   *string          `json:"ipAddress"`
	UserAgent   *string          `json:"userAgent"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

type Company struct {
	ID             string                `json:"id"`
	WorkspaceId    string                `json:"workspaceId"`
	Name           string                `json:"name"`
	Website        *string               `json:"website"`
	Linkedin       *string               `json:"linkedin"`
	CreatedAt      pgtype.Timestamp      `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp      `json:"updatedAt"`
	LegalName      *string               `json:"legalName"`
	Phone          *string               `json:"phone"`
	Instagram      *string               `json:"instagram"`
	PolicyUrl      *string               `json:"policyUrl"`
	SocialUrls     []byte                `json:"socialUrls"`
	AddressLine    *string               `json:"addressLine"`
	City           *string               `json:"city"`
	State          *string               `json:"state"`
	Country        *string               `json:"country"`
	Timezone       *string               `json:"timezone"`
	Currency       *string               `json:"currency"`
	Locale         *string               `json:"locale"`
	BusinessHours  []byte                `json:"businessHours"`
	SupportHours   []byte                `json:"supportHours"`
	DeletedAt      pgtype.Timestamp      `json:"deletedAt"`
	DeletedById    *string               `json:"deletedById"`
	Size           NullCompanySize       `json:"size"`
	Revenue        *float64              `json:"revenue"`
	CompanyScore   int32                 `json:"companyScore"`
	LifecycleStage CompanyLifecycleStage `json:"lifecycleStage"`
	AssignedToId   *string               `json:"assignedToId"`
	CreatedById    *string               `json:"createdById"`
	UpdatedById    *string               `json:"updatedById"`
}

type CompanyTag struct {
	ID        string           `json:"id"`
	CompanyId string           `json:"companyId"`
	TagId     string           `json:"tagId"`
	UserId    string           `json:"userId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Contact struct {
	ID                string                `json:"id"`
	FullName          string                `json:"fullName"`
	WorkspaceId       string                `json:"workspaceId"`
	CreatedAt         pgtype.Timestamp      `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp      `json:"updatedAt"`
	Email             *string               `json:"email"`
	Notes             *string               `json:"notes"`
	Phone             *string               `json:"phone"`
	FirstName         *string               `json:"firstName"`
	LastName          *string               `json:"lastName"`
	Image             *string               `json:"image"`
	Whatsapp          *string               `json:"whatsapp"`
	LinkedinUrl       *string               `json:"linkedinUrl"`
	Language          *string               `json:"language"`
	Timezone          *string               `json:"timezone"`
	City              *string               `json:"city"`
	State             *string               `json:"state"`
	Country           *string               `json:"country"`
	JobTitle          *string               `json:"jobTitle"`
	Department        *string               `json:"department"`
	DecisionRole      *string               `json:"decisionRole"`
	TagLabels         []string              `json:"tagLabels"`
	Source            *string               `json:"source"`
	LastInteractionAt pgtype.Timestamp      `json:"lastInteractionAt"`
	OwnerId           *string               `json:"ownerId"`
	SocialUrls        []byte                `json:"socialUrls"`
	CompanyId         *string               `json:"companyId"`
	DeletedAt         pgtype.Timestamp      `json:"deletedAt"`
	DeletedById       *string               `json:"deletedById"`
	ContactScore      int32                 `json:"contactScore"`
	LifecycleStage    ContactLifecycleStage `json:"lifecycleStage"`
	AssignedToId      *string               `json:"assignedToId"`
	CreatedById       *string               `json:"createdById"`
	UpdatedById       *string               `json:"updatedById"`
}

type ContactTag struct {
	ID        string           `json:"id"`
	ContactId string           `json:"contactId"`
	TagId     string           `json:"tagId"`
	UserId    string           `json:"userId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Deal struct {
	ID                string           `json:"id"`
	WorkspaceId       string           `json:"workspaceId"`
	PipelineId        string           `json:"pipelineId"`
	StageId           *string          `json:"stageId"`
	ContactId         *string          `json:"contactId"`
	Name              string           `json:"name"`
	Value             *float64         `json:"value"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
	DeletedAt         pgtype.Timestamp `json:"deletedAt"`
	DeletedById       *string          `json:"deletedById"`
	Description       *string          `json:"description"`
	Currency          string           `json:"currency"`
	Stage             DealStage        `json:"stage"`
	Probability       *int32           `json:"probability"`
	ExpectedCloseDate pgtype.Timestamp `json:"expectedCloseDate"`
	ClosedAt          pgtype.Timestamp `json:"closedAt"`
	LostReason        *string          `json:"lostReason"`
	CompanyId         *string          `json:"companyId"`
	OwnerId           *string          `json:"ownerId"`
	CreatedById       string           `json:"createdById"`
	UpdatedById       *string          `json:"updatedById"`
}

type DealTag struct {
	ID        string           `json:"id"`
	DealId    string           `json:"dealId"`
	TagId     string           `json:"tagId"`
	UserId    string           `json:"userId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type IdempotencyKey struct {
	ID          string           `json:"id"`
	Key         string           `json:"key"`
	WorkspaceId string           `json:"workspaceId"`
	Response    []byte           `json:"response"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	ExpiresAt   pgtype.Timestamp `json:"expiresAt"`
}

type Organization struct {
	ID               string           `json:"id"`
	Name             string           `json:"name"`
	Document         *string          `json:"document"`
	BillingAddressId *string          `json:"billingAddressId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
}

type Pipeline struct {
	ID          string           `json:"id"`
	WorkspaceId string           `json:"workspaceId"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	IsDefault   bool             `json:"isDefault"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type PipelineStage struct {
	ID          string           `json:"id"`
	PipelineId  *string          `json:"pipelineId"`
	WorkspaceId string           `json:"workspaceId"`
	Name        string           `json:"name"`
	OrderIndex  int32            `json:"orderIndex"`
	Color       *string          `json:"color"`
	Group       StageGroup       `json:"group"`
	Type        PipelineType     `json:"type"`
	IsLocked    bool             `json:"isLocked"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type Tag struct {
	ID          string           `json:"id"`
	WorkspaceId string           `json:"workspaceId"`
	Name        string           `json:"name"`
	Category    TagCategory      `json:"category"`
	Color       string           `json:"color"`
	Description *string          `json:"description"`
	IsSystem    bool             `json:"isSystem"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type Task struct {
	ID           string           `json:"id"`
	Title        string           `json:"title"`
	WorkspaceId  string           `json:"workspaceId"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
	Description  *string          `json:"description"`
	Status       TaskStatus       `json:"status"`
	Priority     Priority         `json:"priority"`
	Type         NullTaskType     `json:"type"`
	TaskType     string           `json:"taskType"`
	ReminderType string           `json:"reminderType"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	CompletedAt  pgtype.Timestamp `json:"completedAt"`
	DeletedAt    pgtype.Timestamp `json:"deletedAt"`
	CompanyId    *string          `json:"companyId"`
	ContactId    *string          `json:"contactId"`
	DealId       *string          `json:"dealId"`
	AssignedToId *string          `json:"assignedToId"`
	StageId      *string          `json:"stageId"`
}

type User struct {
	ID             string           `json:"id"`
	SupabaseUserID *string          `json:"supabaseUserId"`
	Name           *string          `json:"name"`
	Email          *string          `json:"email"`
	EmailVerified  pgtype.Timestamp `json:"emailVerified"`
	Image          *string          `json:"image"`
	DeletedAt      pgtype.Timestamp `json:"deletedAt"`
	AdminRoleId    *string          `json:"adminRoleId"`
	Preferences    []byte           `json:"preferences"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
	Cargo          *string          `json:"cargo"`
	Celular        *string          `json:"celular"`
}

type Workspace struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	Slug                   string           `json:"slug"`
	OwnerId                string           `json:"ownerId"`
	OrganizationId         string           `json:"organizationId"`
	CreatedAt              pgtype.Timestamp `json:"createdAt"`
	UpdatedAt              pgtype.Timestamp `json:"updatedAt"`
	StripeCustomerID       *string          `json:"stripeCustomerId"`
	StripeSubscriptionID   *string          `json:"stripeSubscriptionId"`
	StripePriceID          *string          `json:"stripePriceId"`
	StripeCurrentPeriodEnd pgtype.Timestamp `json:"stripeCurrentPeriodEnd"`
	GeocodingUsage         int32            `json:"geocodingUsage"`
}

type WorkspaceMember struct {
	ID              string           `json:"id"`
	UserId          string           `json:"userId"`
	WorkspaceId     string           `json:"workspaceId"`
	WorkspaceRoleId string           `json:"workspaceRoleId"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
}

type WorkspaceRole struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
