// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio.sql

package sqlc

import (
	"context"
)

const createPortfolioItem = `-- name: CreatePortfolioItem :one
INSERT INTO "PortfolioItem" (
    "id",
    "workspaceId",
    "name",
    "description",
    "sku",
    "category",
    "vertical",
    "status",
    "visibility",
    "basePrice",
    "currency",
    "imageUrl",
    "metadata",
    "tags",
    "createdById",
    "updatedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, CURRENT_TIMESTAMP
)
RETURNING id, "workspaceId", name, description, sku, category, vertical, status, visibility, "basePrice", currency, "imageUrl", metadata, tags, "createdById", "updatedById", "createdAt", "updatedAt", "deletedAt"
`

type CreatePortfolioItemParams struct {
	ID          string                `json:"id"`
	WorkspaceId string                `json:"workspaceId"`
	Name        string                `json:"name"`
	Description *string               `json:"description"`
	Sku         *string               `json:"sku"`
	Category    PortfolioCategoryEnum `json:"category"`
	Vertical    PortfolioVertical     `json:"vertical"`
	Status      PortfolioStatus       `json:"status"`
	Visibility  PortfolioVisibility   `json:"visibility"`
	BasePrice   float64               `json:"basePrice"`
	Currency    string                `json:"currency"`
	ImageUrl    *string               `json:"imageUrl"`
	Metadata    []byte                `json:"metadata"`
	Tags        []string              `json:"tags"`
	CreatedById string                `json:"createdById"`
}

func (q *Queries) CreatePortfolioItem(ctx context.Context, arg CreatePortfolioItemParams) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, createPortfolioItem,
		arg.ID,
		arg.WorkspaceId,
		arg.Name,
		arg.Description,
		arg.Sku,
		arg.Category,
		arg.Vertical,
		arg.Status,
		arg.Visibility,
		arg.BasePrice,
		arg.Currency,
		arg.ImageUrl,
		arg.Metadata,
		arg.Tags,
		arg.CreatedById,
	)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.Name,
		&i.Description,
		&i.Sku,
		&i.Category,
		&i.Vertical,
		&i.Status,
		&i.Visibility,
		&i.BasePrice,
		&i.Currency,
		&i.ImageUrl,
		&i.Metadata,
		&i.Tags,
		&i.CreatedById,
		&i.UpdatedById,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePortfolioItem = `-- name: DeletePortfolioItem :exec
UPDATE "PortfolioItem"
SET "deletedAt" = CURRENT_TIMESTAMP
WHERE "workspaceId" = $1 AND "id" = $2
`

type DeletePortfolioItemParams struct {
	WorkspaceId string `json:"workspaceId"`
	ID          string `json:"id"`
}

func (q *Queries) DeletePortfolioItem(ctx context.Context, arg DeletePortfolioItemParams) error {
	_, err := q.db.Exec(ctx, deletePortfolioItem, arg.WorkspaceId, arg.ID)
	return err
}

const getPortfolioItem = `-- name: GetPortfolioItem :one
SELECT id, "workspaceId", name, description, sku, category, vertical, status, visibility, "basePrice", currency, "imageUrl", metadata, tags, "createdById", "updatedById", "createdAt", "updatedAt", "deletedAt" FROM "PortfolioItem"
WHERE "workspaceId" = $1 AND "id" = $2 AND "deletedAt" IS NULL
`

type GetPortfolioItemParams struct {
	WorkspaceId string `json:"workspaceId"`
	ID          string `json:"id"`
}

func (q *Queries) GetPortfolioItem(ctx context.Context, arg GetPortfolioItemParams) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, getPortfolioItem, arg.WorkspaceId, arg.ID)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.Name,
		&i.Description,
		&i.Sku,
		&i.Category,
		&i.Vertical,
		&i.Status,
		&i.Visibility,
		&i.BasePrice,
		&i.Currency,
		&i.ImageUrl,
		&i.Metadata,
		&i.Tags,
		&i.CreatedById,
		&i.UpdatedById,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPortfolioItems = `-- name: ListPortfolioItems :many
SELECT id, "workspaceId", name, description, sku, category, vertical, status, visibility, "basePrice", currency, "imageUrl", metadata, tags, "createdById", "updatedById", "createdAt", "updatedAt", "deletedAt" FROM "PortfolioItem"
WHERE "workspaceId" = $1
  AND "deletedAt" IS NULL
  AND ($2::"PortfolioStatus" IS NULL OR "status" = $2)
  AND ($3::"PortfolioCategoryEnum" IS NULL OR "category" = $3)
  AND ($4::TEXT IS NULL OR "name" ILIKE '%' || $4 || '%' OR "description" ILIKE '%' || $4 || '%')
ORDER BY "createdAt" DESC
`

type ListPortfolioItemsParams struct {
	WorkspaceId string                    `json:"workspaceId"`
	Status      NullPortfolioStatus       `json:"status"`
	Category    NullPortfolioCategoryEnum `json:"category"`
	Query       *string                   `json:"query"`
}

func (q *Queries) ListPortfolioItems(ctx context.Context, arg ListPortfolioItemsParams) ([]PortfolioItem, error) {
	rows, err := q.db.Query(ctx, listPortfolioItems,
		arg.WorkspaceId,
		arg.Status,
		arg.Category,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortfolioItem{}
	for rows.Next() {
		var i PortfolioItem
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceId,
			&i.Name,
			&i.Description,
			&i.Sku,
			&i.Category,
			&i.Vertical,
			&i.Status,
			&i.Visibility,
			&i.BasePrice,
			&i.Currency,
			&i.ImageUrl,
			&i.Metadata,
			&i.Tags,
			&i.CreatedById,
			&i.UpdatedById,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortfolioItem = `-- name: UpdatePortfolioItem :one
UPDATE "PortfolioItem"
SET
    "name" = COALESCE($4, "name"),
    "description" = COALESCE($5, "description"),
    "sku" = COALESCE($6, "sku"),
    "category" = COALESCE($7, "category"),
    "vertical" = COALESCE($8, "vertical"),
    "status" = COALESCE($9, "status"),
    "visibility" = COALESCE($10, "visibility"),
    "basePrice" = COALESCE($11, "basePrice"),
    "currency" = COALESCE($12, "currency"),
    "imageUrl" = COALESCE($13, "imageUrl"),
    "metadata" = COALESCE($14, "metadata"),
    "tags" = COALESCE($15, "tags"),
    "updatedById" = $3,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "workspaceId" = $1 AND "id" = $2 AND "deletedAt" IS NULL
RETURNING id, "workspaceId", name, description, sku, category, vertical, status, visibility, "basePrice", currency, "imageUrl", metadata, tags, "createdById", "updatedById", "createdAt", "updatedAt", "deletedAt"
`

type UpdatePortfolioItemParams struct {
	WorkspaceId string                    `json:"workspaceId"`
	ID          string                    `json:"id"`
	UpdatedById *string                   `json:"updatedById"`
	Name        *string                   `json:"name"`
	Description *string                   `json:"description"`
	Sku         *string                   `json:"sku"`
	Category    NullPortfolioCategoryEnum `json:"category"`
	Vertical    NullPortfolioVertical     `json:"vertical"`
	Status      NullPortfolioStatus       `json:"status"`
	Visibility  NullPortfolioVisibility   `json:"visibility"`
	BasePrice   *float64                  `json:"basePrice"`
	Currency    *string                   `json:"currency"`
	ImageUrl    *string                   `json:"imageUrl"`
	Metadata    []byte                    `json:"metadata"`
	Tags        []string                  `json:"tags"`
}

func (q *Queries) UpdatePortfolioItem(ctx context.Context, arg UpdatePortfolioItemParams) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, updatePortfolioItem,
		arg.WorkspaceId,
		arg.ID,
		arg.UpdatedById,
		arg.Name,
		arg.Description,
		arg.Sku,
		arg.Category,
		arg.Vertical,
		arg.Status,
		arg.Visibility,
		arg.BasePrice,
		arg.Currency,
		arg.ImageUrl,
		arg.Metadata,
		arg.Tags,
	)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceId,
		&i.Name,
		&i.Description,
		&i.Sku,
		&i.Category,
		&i.Vertical,
		&i.Status,
		&i.Visibility,
		&i.BasePrice,
		&i.Currency,
		&i.ImageUrl,
		&i.Metadata,
		&i.Tags,
		&i.CreatedById,
		&i.UpdatedById,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
