// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Criar nova task retornando o registro completo
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	// =====================================================
	// Task Queries (Schema Real Sincronizado)
	// =====================================================
	// IMPORTANTE: Campos seguem schema real do Prisma
	// IDs são TEXT, não UUID
	// =====================================================
	// Buscar task por ID com isolamento multi-tenant
	GetTask(ctx context.Context, arg GetTaskParams) (GetTaskRow, error)
	// Listar tasks com filtros opcionais
	ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error)
}

var _ Querier = (*Queries)(nil)
