// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO "Task" (
    "id", "title", "workspaceId", "description",
    "status", "priority", "type", "dueDate", "assignedToId"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING 
    "id", "title", "workspaceId", "description",
    "status", "priority", "type", "taskType", "reminderType",
    "dueDate", "completedAt", "deletedAt",
    "companyId", "contactId", "dealId", "assignedToId", "stageId",
    "createdAt", "updatedAt"
`

type CreateTaskParams struct {
	ID           string           `json:"id"`
	Title        string           `json:"title"`
	WorkspaceId  string           `json:"workspaceId"`
	Description  *string          `json:"description"`
	Status       TaskStatus       `json:"status"`
	Priority     Priority         `json:"priority"`
	Type         NullTaskType     `json:"type"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	AssignedToId *string          `json:"assignedToId"`
}

type CreateTaskRow struct {
	ID           string           `json:"id"`
	Title        string           `json:"title"`
	WorkspaceId  string           `json:"workspaceId"`
	Description  *string          `json:"description"`
	Status       TaskStatus       `json:"status"`
	Priority     Priority         `json:"priority"`
	Type         NullTaskType     `json:"type"`
	TaskType     string           `json:"taskType"`
	ReminderType string           `json:"reminderType"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	CompletedAt  pgtype.Timestamp `json:"completedAt"`
	DeletedAt    pgtype.Timestamp `json:"deletedAt"`
	CompanyId    *string          `json:"companyId"`
	ContactId    *string          `json:"contactId"`
	DealId       *string          `json:"dealId"`
	AssignedToId *string          `json:"assignedToId"`
	StageId      *string          `json:"stageId"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

// Criar nova task retornando o registro completo
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.Title,
		arg.WorkspaceId,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Type,
		arg.DueDate,
		arg.AssignedToId,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.WorkspaceId,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Type,
		&i.TaskType,
		&i.ReminderType,
		&i.DueDate,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.CompanyId,
		&i.ContactId,
		&i.DealId,
		&i.AssignedToId,
		&i.StageId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one

SELECT 
    "id", "title", "workspaceId", "description",
    "status", "priority", "type", "taskType", "reminderType",
    "dueDate", "completedAt", "deletedAt",
    "companyId", "contactId", "dealId", "assignedToId", "stageId",
    "createdAt", "updatedAt"
FROM "Task"
WHERE "id" = $1 
  AND "workspaceId" = $2 
  AND "deletedAt" IS NULL
`

type GetTaskParams struct {
	ID          string `json:"id"`
	WorkspaceId string `json:"workspaceId"`
}

type GetTaskRow struct {
	ID           string           `json:"id"`
	Title        string           `json:"title"`
	WorkspaceId  string           `json:"workspaceId"`
	Description  *string          `json:"description"`
	Status       TaskStatus       `json:"status"`
	Priority     Priority         `json:"priority"`
	Type         NullTaskType     `json:"type"`
	TaskType     string           `json:"taskType"`
	ReminderType string           `json:"reminderType"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	CompletedAt  pgtype.Timestamp `json:"completedAt"`
	DeletedAt    pgtype.Timestamp `json:"deletedAt"`
	CompanyId    *string          `json:"companyId"`
	ContactId    *string          `json:"contactId"`
	DealId       *string          `json:"dealId"`
	AssignedToId *string          `json:"assignedToId"`
	StageId      *string          `json:"stageId"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

// =====================================================
// Task Queries (Schema Real Sincronizado)
// =====================================================
// IMPORTANTE: Campos seguem schema real do Prisma
// IDs são TEXT, não UUID
// =====================================================
// Buscar task por ID com isolamento multi-tenant
func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.WorkspaceId)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.WorkspaceId,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Type,
		&i.TaskType,
		&i.ReminderType,
		&i.DueDate,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.CompanyId,
		&i.ContactId,
		&i.DealId,
		&i.AssignedToId,
		&i.StageId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT 
    "id", "title", "workspaceId", "description",
    "status", "priority", "type", "taskType", "reminderType",
    "dueDate", "completedAt", "deletedAt",
    "companyId", "contactId", "dealId", "assignedToId", "stageId",
    "createdAt", "updatedAt"
FROM "Task"
WHERE "workspaceId" = $1 
  AND "deletedAt" IS NULL
  AND ($3::"TaskStatus" IS NULL OR "status" = $3)
  AND ($4::"Priority" IS NULL OR "priority" = $4)
ORDER BY "createdAt" DESC
LIMIT $2
`

type ListTasksParams struct {
	WorkspaceId    string         `json:"workspaceId"`
	Limit          int32          `json:"limit"`
	FilterStatus   NullTaskStatus `json:"filterStatus"`
	FilterPriority NullPriority   `json:"filterPriority"`
}

type ListTasksRow struct {
	ID           string           `json:"id"`
	Title        string           `json:"title"`
	WorkspaceId  string           `json:"workspaceId"`
	Description  *string          `json:"description"`
	Status       TaskStatus       `json:"status"`
	Priority     Priority         `json:"priority"`
	Type         NullTaskType     `json:"type"`
	TaskType     string           `json:"taskType"`
	ReminderType string           `json:"reminderType"`
	DueDate      pgtype.Timestamp `json:"dueDate"`
	CompletedAt  pgtype.Timestamp `json:"completedAt"`
	DeletedAt    pgtype.Timestamp `json:"deletedAt"`
	CompanyId    *string          `json:"companyId"`
	ContactId    *string          `json:"contactId"`
	DealId       *string          `json:"dealId"`
	AssignedToId *string          `json:"assignedToId"`
	StageId      *string          `json:"stageId"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

// Listar tasks com filtros opcionais
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.WorkspaceId,
		arg.Limit,
		arg.FilterStatus,
		arg.FilterPriority,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.WorkspaceId,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Type,
			&i.TaskType,
			&i.ReminderType,
			&i.DueDate,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.CompanyId,
			&i.ContactId,
			&i.DealId,
			&i.AssignedToId,
			&i.StageId,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
